


post http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username": "buddy",
    "role": "software dev",
    "password": "12345"
}

###
GET http://127.0.0.1:5000/api/historical_data/
###

GET http://127.0.0.1:5000/api/UCS_virginstress/

###
GET http://127.0.0.1:5000/api/SRF_hist/



###
post http://127.0.0.1:5000/api/Jn_model
Content-Type: application/json

{
    "description": 0
}

###
POST http://127.0.0.1:5000/api/Jn_model_save
Content-Type: application/json

{
    "Jn_PredictedValue": 32
}

####
GET http://127.0.0.1:5000/api/get_Jn_model



###
post http://127.0.0.1:5000/api/Ja_model
Content-Type: application/json

{
    "description": 23
}

###
post http://127.0.0.1:5000/api/Jr_model
Content-Type: application/json

{
    "description": 200
}


###
post http://127.0.0.1:5000/api/Jw_model
Content-Type: application/json

{
    "description": 200
}
### 
post http://127.0.0.1:5000/api/rmr_model
Content-Type: application/json

{
    "Q_Value": 0.069333
    
}

###
post http://127.0.0.1:5000/api/mus_model
Content-Type: application/json

{
    "Q_Value": 0.123,
    "ESR_VALUE": 1.213
}


###
post http://127.0.0.1:5000/api/Jw_model
Content-Type: application/json

{
    "description": 10
}

###
post http://127.0.0.1:5000/api/q_model
Content-Type: application/json

{
    "RQD": 52.00, 
    "Jn" : 12, 
    "Jr" :  2.0, 
    "Ja" : 2.0,  
    "Jw" : 0.40,
    "SRF" : 7
}

###
post http://127.0.0.1:5000/api/srf_model
Content-Type: application/json

{
    "Virgin_stress_ratio": 15.757250
}

###

post http://127.0.0.1:5000/api/srf_model_save
Content-Type: application/json

{
    "SRF_PredictedValue": 1500,
   
}

###
GET http://127.0.0.1:5000/api/get_srf_model


###

# ESR not working
post http://127.0.0.1:5000/api/esr_model
Content-Type: application/json

{
    "ESR_Conditions": 5
}

###
post http://127.0.0.1:5000/api/ucs_model
Content-Type: application/json

{    
    "Density" : 27000.0,
    "Depth" : 11.98,
    "UCS" : 50.0
}

###
post http://127.0.0.1:5000/api/ucs_model_save
Content-Type: application/json

{    
    "Density" : 27000.0,
    "Depth" : 11.98,
    "UCS" : 50.0,
    "PredictedValue" : 4.5
}

###
get http://127.0.0.1:5000/api/get_ucs_model










###
post http://127.0.0.1:5000/api/rqd_model
Content-Type: application/json

{
    
    "DepthFrom": 9.42,
    "DepthTo": 10.6,
    "TrueThickness": 8.47,
    "Hardness": 3.0
}

###
post http://127.0.0.1:5000/api/RQD_model_save
Content-Type: application/json

{
    
    "Depth_From": 9.42,
    "Depth_To": 10.6,
    "True_Thickness": 8.47,
    "Hardness": 3.0,
    "RQD_PredictedValue": 89
}

###

get http://127.0.0.1:5000/api/get_Q_model


###


post http://127.0.0.1:5000/api/Q_model_save
Content-Type: application/json

{
    
    "Jn_PredictedValue": 9,
    "Jr_PredictedValue": 10,
    "Ja_PredictedValue": 87,
    "Jw_PredictedValue": 3,
    "SRF_PredictedValue": 13,
    "RQD_PredictedValue": 33,
    "Q_Value_PredictedValue": 89
}

####
get http://127.0.0.1:5000/api/get_RMR_model

###


post http://127.0.0.1:5000/api/RMR_model_save
Content-Type: application/json

{
    "RMR_PredictedValue": 89
}
###

get http://127.0.0.1:5000/api/get_ESR_model

###
post http://127.0.0.1:5000/api/ESR_model_save
Content-Type: application/json

{
    "ESR_PredictedValue": 20
}
###

get http://127.0.0.1:5000/api/get_MUS_model


###
get http://127.0.0.1:5000/api/historical_data/